//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public long EnrollmentID { get; set; }
        public Nullable<long> CourseID { get; set; }
        public Nullable<long> StudentID { get; set; }
        public Nullable<int> Grade { get; set; }
    }
}
